### PR TITLE
add value on runtime

### PR DESCRIPTION
**Pull request by Studgi**

### CODE REVIEW

**Review by RestartFU — COMMENTED** [review]
can't we use dragonfly's atomic here to use a `atomic.Value[map[string]any]` instead? would be better

**Comment by Studgi** [comment]
Just found out there's sync.Map which makes things way simpler. Will open another pull request

**Comment by RestartFU** [comment]
> Just found out there's sync.Map which makes things way simpler. Will open another pull request

you could have just committed on your fork but alr

**Comment by Studgi** [comment]
Ohhh oops lol

**Pull request closed without merging**
